language: node_js
node_js:
- '10'

cache:
  directories:
    - $HOME/.npm

install:
  - npm ci

script:
  - CI=false npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: QAFBgIZsDcOSvqyNdfgp/YVBOQevMe8xhn9OVxDmpNF5zMjyzjt1feBF69hPrhmjILmyo5eaSoo5Ca5WTPrw5ayeF0CNmmBR+DUsV1vPLAzyCWV7cn9SpqwSB6Q/0HGAgNbcNgb9wcsCX1/o2qQQ2ZngA2jLtyk4pqTvwjVV/O8Y5domCsJ1ixl/r3sBW5NCISLyd9gIXoOt36St1v5Im8xa9NpXVHtoTjT9oHUKUUFW//y2j/sDcOktGY3vD+qHsOvIdvsSfPYj3s9P/cuLUEeb3vVY14TyixyymiyOYGR+SCUOXDTbFEIUAiMyR05nHAxOfiSRvAgDkCqxSE4XUK0QbD7//NHbs8qj1NKjMU17dL5a/J3wXPrsGI/VU3wepvYJ6GbaIAolCV5mk1iEws9DNmB2ckmGwjhilstA/KSNhAKesCiza7S8Xv2+RrgkcPXi5aoY9CM7uifDTmojO90KSXOPIAQrihalTucZQ2xIeoDrZzy71vmYAGcbo2xqyp2Bz0efEhbfePUwwr+/Rmxo0GQEvjURhKBONxDzg4M2hGK5OA1Hkqf8UlFz47iNjoBy94LEX4h37HadJgUBAFqdq259RjzBI67BCN1G/sCNjY4rmzR+cUZz/i2btyKCdyKlcPnPkGeFdS/QiWIJ3s5CWx7yUUMaJaH3kGYrFHs=
  project: ci-activity
