language: node_js
node_js:
- '10'

cache:
  directories:
    - $HOME/.npm

install:
  - npm ci

script:
  - CI=false npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: aExZrQT+cMLJ6IUm8+AaRFU6aKdm750i6Dqd+ZZpfuv3U2uQzSsqLh2X6P5/PxkEphusNPQ6G7x5abHqmrPKzoDN7AzV4zEm5GoV5rmOa2NKrZVQTucO/WG5EQUarAi+JrVTd/f7k+Szc92GU3fSYOTBli4gMR83N1NKPm/8fb4N0diBPqmqyXrUjO3EAsJBGFrQIre5b8+SDLyCHkYme54dAzCaOtQJWZR9FHqapt+9LEf900gfu1SIQrL112K9UtksLCxJ1EooqrZcCUVqJYJCkjT4X+z/IvIEstKwa5NR1O+yEiWXL8n6hrieWlHWmV6Kf3i60WrlRb5zStAstqJKRLKFTQ4UEyGmELDE3g0cJk3MhjNBhOoonTsOrFay2eWmyMpb/RP6GOPVDljOzizUJJTvmKliooNnOvHKAElaquaGtLE/nHB0wl35slrNOi9KvL/UnBV9wazpEPyvso5IO80M+yZSvpY22Qu+yUGhCBfojyporNLRi/jg3Paim+iuGFr29OTFzxLysT35IKakXjxDTjiVW53oRj7WxydgWCo1fSz3LO4qc9ExcA0CsViQljMLyXTiYp4E+7y99LIzrGuCPrl0FlxMoBOdpKI8ZTMAW/iUMJQNWUBGegydjvV9XUQKAsXotnk9NEnLJmC2Nf8MDwbec/f+vtHdvpI=
